name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: test
      run: npm test
    # - name: Docker Vulnerability Scan With Phonito Security
    #   uses: phonito/phonito-scanner-action@v1.0.0
    #    with:
    #       image: myapp:${{ steps.vars.outputs.docker_tag }}
    #       phonito-token: ${{ secrets.PHONITO_TOKEN }}
    #       fail-level: CRITICAL

